# 1. Numpy ndarray 이해하기

Numpy는 특히 벡터 및 행렬 연산에 있어 편의성을 제공하는 라이브러리로, 앞으로 사용하게 될 Pandas와 시각화 표현에 기반이 되는 라이브러리라고 할 수 있다.  
Numpy에서는 기본적으로 array(어레이)라는 단위로 데이터를 관리하고, 이에 대한 연산을 수행할 수 있다.

In [1]:
import numpy as np

## 1차원 array

In [2]:
data = [6, 7.5, 8, 0, 1]

arr1 = np.array(data)
print(arr1)

[6.  7.5 8.  0.  1. ]


In [5]:
arr1.shape # 행렬의 차원

(5,)

In [4]:
arr = np.array([2, 3, 4])
print(arr)

[2 3 4]


## 2. 2차원 array

In [6]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

arr2 = np.array(data2)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
print(arr2.shape) # 2행 4열

(2, 4)


# 3. zeros(), ones(), arange() 함수 기능

In [11]:
# 0으로만 구성된 array 만들기
np.zeros((3, 6)) # 3행 6열

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
# 1로만 구성된 array 만들기
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [13]:
# 연속된 수로 array 만들기
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

---

# Numpy에서 사용 가능한 데이터형(dtype)  
**- int8, int16, int32, int64** : 부호가 있는 [8, 16, 32, 64]비트 정수  

**- uint8, uint16, uint32, uint64** : 부호가 없는 [8, 16, 32, 64]비트 정수  

**- float16, float32, float64, float128** :[16, 32, 64, 128]비트 실수  

**- complex64, complex128, complex256** : [64, 128, 256]비트 복소수  

**- bool** : 불리언 (True 또는 False)  

**- object**: Python 오브젝트 형  

**- string_** : 문자열  

**- unicode_**: 유니코드 문자열

In [14]:
arr1.dtype

dtype('float64')

In [15]:
arr2.dtype

dtype('int32')

In [16]:
# 데이터 타입 직접 지정하기
arr = np.array([1, 2, 3, 4, 5], dtype=np.int64)
print(arr)

[1 2 3 4 5]


In [17]:
arr.dtype

dtype('int64')

In [18]:
# 기존의 타입을 변경하기 astype()
float_arr = arr.astype(np.float64)
print(float_arr)

[1. 2. 3. 4. 5.]


In [19]:
float_arr.dtype

dtype('float64')

---

# array 관련 연산
두 array 간에는 더하기, 빼기, 곱하기, 나누기 등의 연산을 수행할 수 있다. '+', '-', '*', '/' 등과 같이 일반 숫자에 대해 사용하는 연산자를 사용하면 된다.  

이 때, 이러한 더하기, 빼기, 곱하기, 나누기 등의 연산은 두 array 상의 동일한 위치의 성분끼리 이루어지게 되므로, 당연히 **두 array의 모양이 같아야 계산이 가능하다.**  

하나의 array와 일반 숫자 간에 연산을 하는 것도 가능한데, 이 경우 해당 숫자와 array 내 모든 성분 간에 해당 연산이 이루어지게 된다.

In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
arr2 = np.array([[7, 8, 9], [10, 11, 12]], dtype=np.float64)

print(arr1)
print(arr2)

[[1. 2. 3.]
 [4. 5. 6.]]
[[ 7.  8.  9.]
 [10. 11. 12.]]


In [21]:
arr1 + arr2

array([[ 8., 10., 12.],
       [14., 16., 18.]])

In [22]:
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [23]:
arr1 ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
1 / arr1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])